### ISSUE TITLE
Configurable Interface Name

### ISSUE THREAD

**Issue by MitchTalmadge** [linuxserver/docker-wireguard#129]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I would like to have the option to change the default interface name created by this container from `wg0` to something else, such as `wg1`.

I am motivated by running this container on the same network as another container (https://github.com/thrnz/docker-wireguard-pia) which also creates `wg0`. 

## Current Behavior

`wg0` is hardcoded into this container in multiple places, such as here:

https://github.com/linuxserver/docker-wireguard/blob/6838e891ac29faae41964ed47d7cc0a1956784ba/root/etc/services.d/wireguard/run#L3-L10

This means that other containers which use `wg0` will clash with an error like:

```
wg-quick: `wg0' already exists
```

## Alternatives Considered

I could ask the author of https://github.com/thrnz/docker-wireguard-pia to make this change too, but that would only fix this one situation. I feel like it would benefit the entire community using this image to have the option to change this interface name.

I am unsure if there is a way for me to make this change only for myself without having to fork this repository, perhaps by using a "Docker Mod" (which I need to research more), but I am open to other options.

**Comment by aptalca** [comment]
Why do you need to put it in the other container's network?

**Comment by MitchTalmadge** [comment]
> Why do you need to put it in the other container's network?

This container acts as a server for the PIA container which is a client of PIA. In effect, I am using this container to forward traffic through another VPN. It seems easiest to put the containers into the same network. However if there is a way to get two networks to communicate, I am open to it.

You might ask why I don't just use the PIA container as a server as well as a client. That container was not designed to be able to handle clients, and it would detract from the purpose of the container. It is only meant to be a client of PIA. I also worry about how reliable it would be compared to this container which has been specifically designed to work as a server.

**Comment by aptalca** [comment]
You probably don't need to have them use the same network as you can handle it with setting the routes on the host.

In any case, this is too fringe of a feature so you're better off either setting the routes or customizing the container: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by ThatAnonyG** [comment]
Why are you so against the idea of adding this feature? Just curious.

**Comment by aptalca** [comment]
I explained it above.

We can't add every single feature everybody wants, because then the readme and the samples would be pages long and it would create a high barrier of entry for most users. Not to mention the increased support requests from people who won't understand it but think they need to customize it.

**Comment by ThatAnonyG** [comment]
But this is a very simple yet important config. If this is supposed to be hosted on prod then the ability to configure these things should be there. The explanation can be added in readme for each configuration. It sounds as if you are willing to loose the people who want to have the ability configure their servers to keep the people who wants a simple deployment and doesn't want to read any docs let alone a frigging readme.

**Comment by MitchTalmadge** [comment]
I believe the solution would be a link to another page (e.g. wiki) with advanced options and explanations for advanced users. Even beginners should understand that advanced options are not required to get the container up and running. They are by definition...optional. It's not necessary to add these into the main readme, just bury them somewhere. The people who need it will find it. The people who don't will not go looking.

**Comment by ThatAnonyG** [comment]
Yeah that sounds reasonable. I don't understand why advanced users cannot configure as their wish because beginners will get confused.

**Comment by aptalca** [comment]
You can configure and customize as you wish:
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
That is specifically for advanced users.

**Comment by OSMIbra** [comment]
I recently had occasion to do this, so I customized the container as suggested by aptalca and managed to spin up a container with an interface named wg1 instead of wg0. What I did was a bit hacky, but it got the job done, so I'll share my method here.

First, I ```grep```ed the container to find all instances of ```wg0```. Found instances in three files:
```
- /etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
- /etc/s6-overlay/s6-rc.d/svc-wireguard/finish
- /etc/s6-overlay/s6-rc.d/svc-wireguard/run
```
So I decided to create binds to my own edited versions of all three files, in which all occurrences of ```wg0``` would be replaced with ```wg1```. Here are the steps:

1. Create a directory called ```mod```, ideally in the same place where the config folder and (if using compose) the compose file are located.
2. Create two sub-directories in the ```mod``` directory: ```init-confs``` and ```svc-wireguard```.
3. Copy all three files to their corresponding directories in the ```mod``` folder, either directly from the repo, or by  spinning up the container once without any modification and using ```docker cp```:

- ```finish``` and ```run``` files from ```etc/s6-overlay/s6-rc.d/svc-wireguard/``` to ```./mod/svc-wireguard```
- ```run``` file from ```/etc/s6-overlay/s6-rc.d/init-wireguard-confs/``` to ```./mod/init-wireguard-confs```
- If copying from the repo directly, they are under [etc/s6-overlay/s6-rc.d](https://github.com/linuxserver/docker-wireguard/tree/master/root/etc/s6-overlay/s6-rc.d)

4. Use your favorite text editor to replace all instances of ```wg0``` in all three files with the alternative interface name you want to set, for example ```wg1```.
5. Create corresponding bindings to the **files** (not to the directories) in your compose file:
```
volumes:
      - ./mod/svc-wireguard/run:/etc/s6-overlay/s6-rc.d/svc-wireguard/run
      - ./mod/svc-wireguard/finish:/etc/s6-overlay/s6-rc.d/svc-wireguard/finish
      - ./mod/init-confs/run:/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
      - ./config/wg-server:/config #ignore
      - /lib/modules:/lib/modules #ignore
```
I suppose these could be set as ```ro``` bindings, but I've never tested that myself with file bindings.

6. Delete ```wg0.conf``` in your config folder if it exists; it shouldn't affect anything, but the file is no longer needed/used at this point. Then recreate the container using ```docker compose```. Check the logs and hopefully you'll have everything up and running with the interface name that you chose.
