### ISSUE TITLE
Only allow traffic to specified allowed ips

### ISSUE THREAD

**Issue by foerkede** [linuxserver/docker-wireguard#152]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I want to use this container to give some third party developers access to a single server, but not my entire network. Specifying this in the "AllowedIPS" field only sets this on the client peer config, which is editable on the client side. In my understanding wireguard doesn't address this, so there are probably some additional iptables commands needed in the PreUP/PostDown fields of the server config. My experience with iptables is very low, so I thought I'd ask first here before I cook something together myself.
------------------------------

## Desired Behavior

Clients are able to connect only to the IPs specified in the "ALLOWEDIPS" field.

## Current Behavior

The client can change his peer config to elevate access.

## Alternatives Considered

I tried to do some iptables stuff via a new docker network bridge to which the wireguard container is connected, but it broke the whole networking...

**Comment by aptalca** [comment]
ALLOWEDIPs is not what you think it is. It just tells wg what packets to send through the tunnel based on their destination.

There are multiple different ways you can handle that, including setting iptables rules on the host, in the container, or even setting rules on the router (or even vlans). But that's way beyond the scope of github issues. You can seek help on our discord or forum. But keep in mind that we don't provide official support for those requests due to the fact that such setups can widely vary and we don't have the bandwidth to support those scenarios individually.
