### ISSUE TITLE
[FEAT] New env var: CLIENT_ALLOWEDIPS_PEER_<peer name or number>

### ISSUE THREAD

**Issue by FStefanni** [linuxserver/docker-wireguard#273]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi,

I propose to add a new environmental variable, namely `CLIENT_ALLOWEDIPS_PEER_<peer name or number>`, basically with the same semantics as `SERVER_ALLOWEDIPS_PEER_<peer name or number>`.

The difference is: the new variable will populate the `AllowedIPs` with the custom values, inside the client peer configuration (i.e. inside `peer_<peer name or number>.conf` and not inside the server `wg0.conf` file).

Regards

### Reason for change

This is useful for complex scenarios, to customize the behavior of the client peers.
For example, a configuration as described in <https://www.laroberto.com/remote-lan-access-with-wireguard/>

**Comment by aptalca** [comment]
The client confs are user editable. In fact they need to be manually transferred to the client and can/should be edited as necessary then. Therefore there is no need for an env var on the server.

The reason we added the `SERVER_ALLOWEDIPS_PEER_<peer name or number>` as an env var is because that info goes into a section of the `wg0.conf` that is not user editable, and it's auto generated and managed directly by the container, thereby necessitating a var to facilitate the generation and management.

**Comment by FStefanni** [comment]
Hi,

I understand your point, but I was thinking to scenarios of automatic deployment, as pipelines of ci/cd, or in case of the need to regenerate all the certificates. Having an automatic way for regenerating everything, and having a single source of truth for the configuration (in this case the environmental variables), is valuable in these cases. I understand these are not common for normal users/domestic users, but definitely they happen on companies.
That's why I believe it could be an interesting feature.

Regards
