### ISSUE TITLE
wireguard-go option

### ISSUE THREAD

**Issue by vchrisb** [linuxserver/docker-wireguard#63]
## Expected Behavior
work independent of host os kernel modules

## Current Behavior
requires wireguard kernel modules available on the host

## Context

Wireguard does also have a userspace option to run, called wireguard-go (https://git.zx2c4.com/wireguard-go)
It would be great to have a version of docker-wireguard based on that.

**Comment by aptalca** [comment]
This image compiles the kernel modules as long as kernel headers are available (either via ubuntu/debian/raspbian repos or user supplied on host).

Biggest advantages of wireguard are due to running inside the kernel which the user space version lacks.

5.6 has the kernel module built in, and many distros are baking it in even before that (armbian and Pop OS added it in 5.4 iirc) so it's only a matter of time before it's all built in.

**Comment by vchrisb** [comment]
thx @aptalca 
I deployed the image to a rock64 and that required some workarounds, googling etc... that probably changes but there will always be some people having challenges with kernel modules.

I've also deployed it to kubernetes, which works great, but in a k8s cluster one would need to compile them on every host. Finally reducing the dependency of the image from the host is greatly appreciated (no hostpath mount, no SYS_MODULE security context).
For many usecases the performance of the in kernel option is not necessary and in the K8s cluster usecase, I guess a scale out might even work.

**Comment by alphadijkstra** [comment]
Totally agreeing with this feature. Currently trying to set up a Wireguard client on my Qnap NAS. It is a PITA because downloading the headers is just not possible.
Using a userspace version of Wireguard opens up this Docker implementation to many, many more systems. 
Even if that makes it slower than using the kernel, still well worth it to me.

**Comment by aptalca** [comment]
I looked into it and it's not just a drop in replacement. It's a whole another implementation written in go, with different management scripts. I don't have the time (or the interest really) to implement it.

**Comment by tigrang** [comment]
@alphadijkstra I got this working on openvz vps: https://github.com/tigrang/docker-wireguard/commit/184903af0b4e15e1bbb2c4113a06bc01208250bd

You'd want to have somewhere more knowledgeable confirm security aspect of it so use at your own risk.

To run it, need to pass extra env variable ` WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1` and add tun device with `--device=/dev/net/tun`
