### ISSUE TITLE
Wg0.conf unwanted overwrite

### ISSUE THREAD

**Issue by ptruman** [linuxserver/docker-wireguard#70]
## Expected Behavior
Wg0.conf should not be updated on container image update/pull and restart

## Current Behavior
Upgrade to latest yesterday.  Wg0.conf was updated and my PresharedKey line was removed. Client failed to connect.

Restored from backup to regain function.  Config folder is a bind mount for persistence.

Log not available as I'm posting this late (sorry)

May need a check to see if it's native code updating wg0.conf or a boot script?

**Comment by aptalca** [comment]
wg0.conf is regenerated when one of the relevant env vars is changed. If you don't change any of the vars, nothing gets overwritten. Even when it is regenerated, it retains the same public/private keys for the existing users, so it shouldn't prevent them from connecting.

Also, it's very hard to say exactly why what you're saying happened because you didn't fill out the issue template and therefore I'm shooting in the dark.

**Comment by ptruman** [comment]
I just pulled a new image, stuff broke.
wg0.conf lost my PSK which was manually added.

Backup restoration fixed it.  I'll await the next release and double check,
but just wanted to flag it (via mobile, admittedly, late!) :)

The main bones of wg0.conf was good, but PSKs are only manually added so
maybe are not checked for.
